before:
  hooks:
    - mv example.skadi.yml skadi.yml
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: skadi
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      amd64: x86_64
    wrap_in_directory: true
    files:
      - skadi.yml
      - skadi.service
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
