before:
  hooks:
    - mv example.skadi.yml skadi.yml
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: skadi
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      amd64: x86_64
    wrap_in_directory: true
    files:
      - skadi.yml
      - skadi.service
      - LICENSE
      - README.md
nfpms:
  - id: default
    package_name: skadi

    vendor: hack.fan
    homepage: https://letserver.run
    maintainer: hyacinthus <hyacinthus@gmail.com>
    description: |
      Control your service by IM, written in Go
    license: MIT

    formats:
      - deb
      - rpm

    bindir: /usr/bin
    contents:
      - src: ./skadi.service
        dst: /lib/systemd/system/skadi.service

      - src: ./example.skadi.yml
        dst: /etc/skadi/skadi.yml
        type: "config|noreplace"

    scripts:
      postinstall: ./scripts/postinstall.sh
      preremove: ./scripts/preremove.sh
      postremove: ./scripts/postremove.sh

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^ci:'
      - '^docs:'
      - '^test'
      - '^tmp'
      - '^wip'
