name: goreleaser

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Cloudsmith CLI tooling for pushing releases
      - name: Install Cloudsmith CLI
        run: |
          pip install --upgrade cloudsmith-cli
          # Add "pip install" CLI tools to PATH
          echo ~/.local/bin >> $GITHUB_PATH

      # Release by go releaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publish tags to Cloudsmith
      - name: Publish .deb to Cloudsmith
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          for filename in dist/*.deb; do
            echo "Pushing $filename"
            cloudsmith push deb hackfan/skadi/any-distro/any-version $filename
          done
      - name: Publish .rpm to Cloudsmith
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          for filename in dist/*.rpm; do
            echo "Pushing $filename"
            cloudsmith push rpm hackfan/skadi/any-distro/any-version $filename
          done
